services:
  srs:
    image: ossrs/srs:5
    container_name: srs-hls
    ports:
      - "1935:1935" # RTMP
      - "1985:1985" # API
      - "8080:8080" # HTTP Server (for HLS)
      - "8000:8000" # WebRTC
      - "8000:8000/udp" # WebRTC UDP
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
    environment:
      - SRS_LOG_LEVEL=trace
      - SRS_STAT_NETWORK=1
    restart: unless-stopped
    tty: true
    stdin_open: true

  coturn:
    image: coturn/coturn
    container_name: coturn
    restart: always
    environment:
      - REALM=localhost
      - USERNAME=coturn
      - PASSWORD=coturn
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/tcp"
      - "5349:5349/udp"
      - "49160-49200:49160-49200/udp"

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - srs
      - coturn
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
